version: '3.9'
services:
  web:
    build: .
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - redis
  celery:
    build: ./
    command: celery -A shop worker -l info -E
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
  flower:
    build: ./
    command: celery -A shop flower
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/
    ports:
      - 5555:5555
    depends_on:
      - celery
      - redis
  redis:
    image: redis:alpine
